### ISSUE TITLE
Docker build fails with latest version

### ISSUE THREAD

**Issue by stoney27** [jonmbake/discourse-ldap-auth#4]
Hi,

I am getting the following error when I run ./launcher rebuild app in the discourse docker image:

```
Bundled gems are installed into ./vendor/bundle.

I, [2016-01-12T16:36:08.438005 #36]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
rake aborted!
LoadError: cannot load such file -- ./lib/ldap_user
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/var/www/discourse/plugins/ldap/plugin.rb:14:in `activate!'
/var/www/discourse/lib/plugin/instance.rb:308:in `instance_eval'
```

Looks like the addition of this code: 
``` ruby
 gem 'net-ldap', '0.3.1'
 gem 'omniauth-ldap', '1.0.4'
  
 +require 'yaml'
 +require './lib/ldap_user'
 +
  class LDAPAuthenticator < ::Auth::Authenticator
    def name
      'ldap'
    end
```

Maybe the issue.

Thanks.
-Scott

**Comment by jonmbake** [comment]
Hey Scott.

Sorry about that.  This has been fixed in https://github.com/jonmbake/discourse-ldap-auth/commit/4b36e8d1b0c2fbacddfc5df8cfd96a2ae8d4de9c.

Please let me know if you notice any other issues.

Thanks,
Jon
