### ISSUE TITLE
require_relative failing for ldap_auth

### ISSUE THREAD

**Issue by jorymorrison** [jonmbake/discourse-ldap-auth#46]
I'm trying to use your plugin with Bitnami Docker Discourse. 

For reference: https://github.com/bitnami/bitnami-docker-discourse/issues/111 

Short version: No matter how I install the plugin (e.g. in Dockerfile or via shell script with git clone) I am encountering an exception:

```
nami    TRACE Error: Error executing 'postInstallation': rake aborted!
LoadError: cannot load such file -- /opt/bitnami/discourse/plugins/discourse-ldap-auth/lib/ldap_user
/opt/bitnami/discourse/plugins/discourse-ldap-auth/plugin.rb:14:in `require_relative'
/opt/bitnami/discourse/plugins/discourse-ldap-auth/plugin.rb:14:in `activate!'
/opt/bitnami/discourse/lib/plugin/instance.rb:486:in `instance_eval'
/opt/bitnami/discourse/lib/plugin/instance.rb:486:in `activate!'
lib/discourse.rb:171:in `block in activate_plugins!'
lib/discourse.rb:168:in `each'
lib/discourse.rb:168:in `activate_plugins!'
/opt/bitnami/discourse/config/application.rb:261:in `<class:Application>'
/opt/bitnami/discourse/config/application.rb:58:in `<module:Discourse>'
/opt/bitnami/discourse/config/application.rb:57:in `<top (required)>'
/opt/bitnami/discourse/Rakefile:7:in `require'
/opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.execute (/root/.nami/components/com.bitnami.ruby/helpers.js:44:7)
    at Object.$app.helpers.bundleExecute (/root/.nami/components/com.bitnami.ruby/helpers.js:62:8)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at Object.$app.helpers.migrateDatabase (/root/.nami/components/com.bitnami.discourse/helpers.js:235:8)
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.discourse/main.js:58:18)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
```

After sshing into the container, I've determined that sometime during the rake ldap_auth.rb is getting moved out from the lib subdirectory and into the parent plugin directory. It's unclear to me whether this is an issue cause with Bitnami, Plugin, or (more likely) something I'm doing incorrectly. Any help is greatly appreciated.

**Comment by jorymorrison** [comment]
Additionally, the only file present in the lib directory post rake is `auth.rb`.

**Comment by jonmbake** [comment]
@jorymorrison I'll take a look at this in the next couple of days. If you have a fix, feel free to submit a PR.

**Comment by jonmbake** [comment]
I am not sure exactly what is going on here either. The Discourse plugin install process simply does a clone of this repository. So all files in _lib_ should be cloned and remain present. As you noted, something outside of the plugin install process is moving or deleting the file.

Do you have a link to the _Rakefile_ for the rake task that is getting invoked that you suspect might be moving the file?
